---
title: "Wissenschaftliche Publikationen"
---

| Titel | Autoren | Journal / Quelle | Jahr |
|------|---------|----------------|------|
| [Evaluation Metrics for Galaxy Image Generators](https://reader.elsevier.com/reader/sd/pii/S2213133722000993?token=A106C7053945363C27B60407951C56001D87B667747EE564945FDC8A1789EFEF009093D32F69D29CAD21FC4DD7E9516B&originRegion=eu-west-1&originCreation=20230127114549) | Hackstein, S., Kinakh, V., Bailer, C., Melchior, M. | *Astronomy & Computation* | 2023 |
| [Fast radio burst redshift distribution and the missing baryons](https://arxiv.org/pdf/2101.03569.pdf) | Hackstein, S., Brüggen, M., Vazza, F. | *Monthly Notices of the Royal Astronomical Society* | 2021 |
| [Redshift estimates for fast radio bursts and implications on intergalactic magnetic fields](https://arxiv.org/pdf/2008.10536.pdf) | Hackstein, S., Brüggen, M., Vazza, F., Rodrigues, L. F. S. | *MNRAS* | 2020 |
| [PrEFRBLE: Probability Estimates for Fast Radio Bursts to obtain model Likelihood Estimates](https://zenodo.org/record/3862636#.X3GpQ3VfhH4) | Hackstein, S. | [Zenodo](https://zenodo.org/records/3862636)
) | 2020 |
| [Fast radio burst dispersion measures and rotation measures and the origin of intergalactic magnetic fields](https://arxiv.org/pdf/1907.09650.pdf) | Hackstein, S., Vazza, F., Brüggen, M., Gaensler, B. M., Heesen, V. | *MNRAS* | 2019 |
| [Propagation of UHECRs in the local Universe and origin of cosmic magnetic fields](https://arxiv.org/pdf/1902.04408.pdf) | Hackstein, S., Vazza, F., Brüggen, M., Sorce, J. G., Gottlöber, S. | *Proceedings of IAU Focus Meeting 8* | 2019 |
| [Simulations of ultra-high Energy Cosmic Rays in the local Universe and the origin of Cosmic Magnetic Fields](https://arxiv.org/pdf/1710.01353.pdf) | Hackstein, S., Vazza, F., Brüggen, M., Sorce, J. G., Gottlöber, S. | *MNRAS* | 2018 |
| [Propagation of ultrahigh energy cosmic rays in extragalactic magnetic fields: a view from cosmological simulations](https://watermark.silverchair.com/stw1903.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAqgwggKkBgkqhkiG9w0BBwagggKVMIICkQIBADCCAooGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdGjk94HKrGt2F0phAgEQgIICW8WTlqg8Ss5sKATybwKcB4yFnjz6n9aEzMZ9BdSBdnjbDFJ4ubJa3vdHrv8VM62H0KZ-b67gEi_O6uFnvFBaptwlF4mT_2a6fh6XB42tVg-HxmKPxxOmXCwbXtvNNpWaDXLBG1dQGHb4uSjPK4NKH2k012RqM78CVWYPN5nkSvLom_-blJgin2AM4vaZ17JQFtA1i71DjYVPgvImNRsUQVbkY9QX9ofIExOBN97oMHttq6eCrC2fiT7jfO1MjvSEQ2w9nINh2sZppUGSaZTh9qH0AoyWBkIU-GlEVe1D4i3nUKdF9BJMbAWZ0XjIEVDC9PGtWp3LcXZPnrcb7AzstD4DcgPVEFi38B3kyWnIHLiJkPV6ezSBebFt-unZ_QDMJWs5333iMWnO0u2jaca_bAAsDiihmdATFy_Nbob9Vh-mV5W9a5-RP0TpiXL2oPSeca8opxFfTmnh6E-1MFww663MNNWibe9XbowtyhYipQ8xeiuJHBD79XAma2Vp_5gsrND49_OUMsV1JqRWEkaQaLotnqpgH3i8ePidUA5ZxZhRw7EV1LzDvuoYSl6jCP1qfS3waNrNoCCLY6R-6cohoArriF1av2S9lsn9XbATEhzVdRpZBgYvGSCQStpXsKhPc2jYdMXWNUvdePbdt-Yb1F_UsuF1PAvUxZwj_-GsXIc_xvO14aqqrDGKrl891roYF1wppYhRj5DtX85tLu8ta2c8KmWya5WacoQ0cgzvFlULwVcJFcKfq9DQ1zEekpno92UYkeR0uIgdxpSQNm5LwnMSi5gGf09BAYtY3w) | Hackstein, S., Vazza, F., Brüggen, M., Sigl, G., Dundovic, A. | *MNRAS* | 2016 |

Weitere Publikationen als Coautor: [volle Liste](https://scholar.google.com/citations?hl=en&user=9EfAqvwAAAAJ&view_op=list_works&gmla=AJsN-F56OCPsavsMCBVIm7O234YskrKzUS_RMdVJHXJrvWT5JWlpiFnXn_kWn8UvSan6P8QHOzq3MlQ7pQ3_pvrnzeoxv9n4dEeRqIpybRB3dYQBrNYtNL8)
